### ISSUE TITLE
ByteString called #basicNew: with invalid argument from #codeWithEmptyLineMarkersError

### ISSUE THREAD

**Issue by LinqLover** [tom95/poppy-print#7]
Occurs when trying to poppy-print `BaselineOfSimulationStudio>>baseline:`, loadable via https://github.com/LinqLover/SimulationStudio:

https://github.com/LinqLover/SimulationStudio/blob/cad846fdee882e676d5e97ccfb5fad32336d4a6d/packages/BaselineOfSimulationStudio.package/BaselineOfSimulationStudio.class/instance/baseline..st

**Comment by tom95** [comment]
Turns out this was a bug in Squeak's core: http://forum.world.st/The-Inbox-Compiler-tobe-455-mcz-td5127672.html
